#!/usr/bin/env bash

# dmenu theming
lines="-l 3"
font="-fn Inconsolata-15"
colors="-nb #1f223d -nf #43ffe1 -sb #43ffe1 -sf #1f223d"
#colors="-nb #f95d78 -nf #fdf6e3 -sb #e01499 -sf #fdf6e3"

first_prompt="O que você deseja?"
opt1="Sair do i3\nReiniciar\nDesligar"
opt2="Sim\nNão"


ask() {
    answer="$( echo -e $1 | dmenu -i -p "$2" $lines $colors $font )"
}

ask "$opt1" "$first_prompt"

case $answer in
    "Sair do i3")
        # ask "$opt2" "Quer mesmo sair do i3wm?"
        # if [[ $answer == "Sim" ]]; then
             i3-msg exit
        # fi
        exit 0
        ;;
    "Reiniciar")
        # ask "$opt2" "Quer mesmo reiniciar o sistema?"
        # if [[ $answer == "Sim" ]]; then
             systemctl reboot
        # fi
        exit 0
        ;;
    "Desligar")
        # ask "$opt2" "Quer mesmo desligar o computador?"
        # if [[ $answer == "Sim" ]]; then
             systemctl poweroff
        # fi
        exit 0
        ;;
esac

exit 0
